apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  labels:
    app: mqtt-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
        - name: mqtt-broker
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
            - containerPort: 9001
          volumeMounts:
            - name: mqtt-config
              mountPath: /mosquitto/config
      volumes:
        - name: mqtt-config
          hostPath:
            path: mosquitto.conf
            type: File
