apiVersion: apps/v1
kind: Deployment
metadata:
  name: rec-controller
  labels:
    app: rec-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rec-controller
  template:
    metadata:
      labels:
        app: rec-controller
    spec:
      containers:
        - name: rec-controller
          image: microservices-abgabe-rec_controller:latest
          imagePullPolicy: Never
          env:
            - name: MQTT_BROKER
              value: mqtt-broker-service
            - name: NODE_ENV
              value: production
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "ps aux | grep '[n]ode'"
            initialDelaySeconds: 15
            periodSeconds: 10
