apiVersion: v1
kind: ConfigMap
metadata:
  name: rec-controller-config
data:
  MQTT_BROKER: mqtt-service
  NODE_ENV: production
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_USER: cm9vdA==   # "root" base64 encoded
  MONGO_PASS: ZXhhbXBsZQ==  # "example" base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rec-controller
  labels:
    app: rec-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rec-controller
  template:
    metadata:
      labels:
        app: rec-controller
    spec:
      containers:
        - name: rec-controller
          image: rec-controller:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: mongodb-config
            - configMapRef:
                name: rec-controller-config
            - secretRef:
                name: mongo-secret
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: node-modules
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: rec-controller
spec:
  selector:
    app: rec-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
